### ISSUE TITLE
Question about Packaging Droidel into a runnable Jar file

### ISSUE THREAD

**Issue by nuaa040840308** [cuplv/droidel#25]
Hi, I have successfully packaged the droidel souce code into a runnable Jar file using sbt assembly.
Then I import this runnable Jar into a Java project which is based wala.
However, when calling some methods ( AndroidTransformer.scala) in my Java project, I encounter some errors about LayoutParser.scala.

**Comment by sblackshear** [comment]
I've previously had success with packaging Droidel in a JAR/running it using the sbt OneJar plugin. You can take a look at how Hopper does [this](https://github.com/cuplv/hopper/blob/master/build.sbt) if you are interested.
